database:
  host: localhost
  name: reportsystem
  port: 3333
  username: root
  password:

gui:
  report_reasons:
    # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html

    - FEATHER:
        name: FlyHacks
        description: using any sort of fly exploit

    - IRON_SWORD:
        name: KillAura
        description: using a program to fight for them

reports:
  timezone: UTC

  reason:
    min_length: 4
    max_length: 32


messages:
  PREFIX: ""
  reason_too_long: ""
  reason_not_long_enough: ""