name: SigmaReports
version: '1.0'
main: me.josh.reportsystem.PluginMain
description: A report system meant for minigame servers
softdepend: [PlaceholderAPI]
commands:
  report:
    description: Report a player for breaking the rules
  clearrep:
    description: Debug command to delete all reports
  reports:
    description: Displays a menu with all reports, which are able to be filtered.